# ssl-admin configuration
#
# The following values can be changed without affecting your CA key.

KEY_SIZE = 2048
KEY_DAYS = 3650
KEY_CN =
KEY_CRL_LOC = URI:http://CRL_URI


## WARNING!!! ##
#
# Changing the following values has vast consequences.
# These values must match what's in your root CA certificate.

KEY_COUNTRY = XX
KEY_PROVINCE = STATE/PROVINCE
KEY_CITY = CITY
KEY_ORG = ORGANIZATION
KEY_EMAIL = EMAIL_ADDRESS
